name: CD
on:
  push:
    tags:
    # use vMM.mm.pp to publish nonos (library) and cli-vMM.mm.pp to publish nonos-cli
    - v*
    - cli-v*
  pull_request:
    paths:
    - .github/workflows/cd.yml
    - .github/workflows/build-and-publish.yml
    - '*/**/pyproject.toml'
    - CITATION.cff
    - scripts/pre_publish_checks.py

permissions: {}

jobs:
  pre-publish-checks:
    runs-on: ubuntu-latest
    name: pre-publication checks
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        fetch-depth: 0
        persist-credentials: false
    - uses: astral-sh/setup-uv@85856786d1ce8acfbcc2f13a5f3fbd6b938f9f41 # v7.1.2
      with:
        enable-cache: false
    - run: uv run scripts/pre_publish_checks.py

  build-lib:
    name: Build lib package
    needs: [pre-publish-checks]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        persist-credentials: false
    - uses: astral-sh/setup-uv@85856786d1ce8acfbcc2f13a5f3fbd6b938f9f41 # v7.1.2
      with:
        enable-cache: false
    - name: Build distributions
      shell: bash -l {0}
      run: uv build --package nonos
    - uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
      with:
        name: artifacts-nonos
        path: dist

  publish-lib:
    name: Publish nonos release
    needs: [build-lib]
    if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-latest
    environment:
      name: release-nonos
      url: https://pypi.org/p/nonos
    permissions:
      id-token: write
    steps:
    - uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
      with:
        name: artifacts-nonos
        path: dist

    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e # v1.13.0

  build-cli:
    name: Build CLI package
    needs: [pre-publish-checks]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        persist-credentials: false
    - uses: astral-sh/setup-uv@85856786d1ce8acfbcc2f13a5f3fbd6b938f9f41 # v7.1.2
      with:
        enable-cache: false
    - name: Build distributions
      shell: bash -l {0}
      run: uv build --package nonos-cli
    - uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
      with:
        name: artifacts-nonos-cli
        path: dist

  publish-cli:
    name: Publish nonos-cli release
    needs: [build-cli]
    if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/cli-v') }}
    runs-on: ubuntu-latest
    environment:
      name: release-nonos-cli
      url: https://pypi.org/p/nonos-cli
    permissions:
      id-token: write
    steps:
    - uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
      with:
        name: artifacts-nonos-cli
        path: dist

    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e # v1.13.0
